### ISSUE TITLE
Deployment failures

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#1062]
It seems some of the Deployments fails. By my initial research they fail due to the fact that Deploy workflow is run even for PRs. 

Workflow has a prevention for that but obviously it not working:

```yaml
jobs:

  deploy:
    if: >
      ${{ github.event.workflow_run.event == 'push' &&
      github.ref == 'refs/heads/main' &&
      github.event.workflow_run.conclusion == 'success' }}
```

Goal of this issue is to trigger the Deployment only when commit hits the main branch.

![image](https://user-images.githubusercontent.com/193286/149498442-74c6750d-5827-4452-833b-e97935ffe952.png)

**Resources**:

- https://github.com/JamesIves/github-pages-deploy-action
- https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_run
