### ISSUE TITLE
apidom-ls / apidom - Default to schema element for message payload when empty node

### ISSUE THREAD

**Issue by frantuma** [swagger-api/apidom#1076]
@frantuma commented on [Mon Jan 17 2022](https://github.com/swagger-api/oss-planning/issues/501)

Currently an "empty" payload is not parsed as `schema` element using `refractorPluginReplaceEmptyElement` as done for other empty elements. Goal of this ticket is applying the same mechanism also to payload.

Note. The possible reason for this behavior is `payload` type being `any` therefore admitting also non `schema` types.

```
asyncapi: '2.2.0'
components:
  messages:
    lightMeasured:
      payload:
        
```
