### ISSUE TITLE
AsyncAPI: add support for replacing empty elements for nested structures in bindings object

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#1152]
As bindings objects can have internal nested structures, we can support those nested structures via NCEs (Non Concrete Elements). Current plugin for replacing empty elements only recognizes bindings as objects of arbitrary shape. But they actually have a prescribed shape and we can add support for them.

**Comment by frantuma** [comment]
@char0n can you add an exapmple of such "nested structure"? At the moment we support e.g. completion also for empty bindings instances, e.g.

```
asyncapi: '2.2.0'
components:
  messages:
    lightMeasured:
      name: lightMeasured
      bindings: 
        http: 
         
```

this works because the empty value for `http` is recognized as element `http-message-binding`. Is that strucure you meant, or internal to the binding?
