### ISSUE TITLE
apidom-ls: do not validate unknown specs as AsyncAPI 2.x

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#1582]
**Current behavior**

I've noticed that `apidom-ls` validates unknown specs as AsyncAPI 2.x. 

**Expected behavior**

`apidom-ls` detects that spec is not AsyncAPI 2.x and will not do any validations, nor other things like autompletion or documentation.

**Fixture that is detected as AsyncAPI 2.x**

```yaml
#%RAML 1.0
title: GitHub API
version: v3
baseUri: https://api.github.com
mediaType:  application/json
securitySchemes:
  oauth_2_0: !include securitySchemes/oauth_2_0.raml
types:
  Gist:  !include types/gist.raml
  Gists: !include types/gists.raml
resourceTypes:
  collection: !include types/collection.raml
traits:
securedBy: [ oauth_2_0 ]
/users:
  type: collection
```
