### ISSUE TITLE
Enhancement to "Object includes not allowed field"

### ISSUE THREAD

**Issue by ponelat** [swagger-api/apidom#1635]
### Is your feature request related to a problem?

The validation error of "Object includes not allowed field" does not tell me which field isn't allowed.
I'd like it to include that info.

### Additional context
Viewing this in swagger editor validation panel of editor-next.swagger.io
![image](https://user-images.githubusercontent.com/8438485/175030239-2116a2a3-6c9a-4a4e-88f7-abcdbd36e993.png)

```yml
asyncapi: '2.4.0'
info:
  title: What is wrong?
  version: '1.0.0'

channels:
  pets.added:
    description: The topic for newly added Pets.
    publish:
      message:
        foo: true
```
