### ISSUE TITLE
Add validation/autosuggest rules for message.examples (AsyncAPI)

### ISSUE THREAD

**Issue by ponelat** [swagger-api/apidom#1636]
This is to add rules (validation and autosuggestion) for message.examples in AsyncAPI (2.x)
Eg:
```yml
channels:
  pets.added:
    description: The topic for newly added Pets.
    publish:
      message:
        examples: 
          - # <--- what goes here.
```
I had to read up the documenation around examples, because it wasn't "just" the example body, it was a wrapper.
