### ISSUE TITLE
Configure dependabot to auto-update GitHub Actions

### ISSUE THREAD

**Issue by char0n** [swagger-api/apidom#2598]
``` 
 - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
```
