### ISSUE TITLE
apidom-ls: False positive for linting rule ASYNCAPI2_MESSAGE_TRAIT_FIELD_EXAMPLES_ITEMS_TYPE

### ISSUE THREAD

**Issue by CalemRoelofsSB** [swagger-api/apidom#3761]
### Q&A (please complete the following information)
 - OS: MacOS Sonoma 14.3
 - Browser: Firefox 122.0
 - ApiDOM version: 0.87.0
 - Swagger/OpenAPI version: AsyncAPI 2.X.0

### Describe the bug you're encountering
When testing the below AsyncAPI definition on https://editor-next.swagger.io/ v5.0.0-alpha.87, the linting rule [`'examples' must be an array of Message Example Objects`](https://github.com/swagger-api/apidom/blob/d6133c24040a735e13c530ab480abf890b33f7f3/packages/apidom-ls/src/config/asyncapi/message-trait/lint/examples--items-type.ts) is triggered, despite the objects in the `examples` array conforming to the JSON Schema specified in the parent object.

```yaml
asyncapi: '2.6.0'
info:
  title: Title
  version: '1.0.0'
  description: 'description'
channels: {}
components:
  messageTraits:
    commonHeaders:
      headers:
        type: object
        properties:
          my-app-header:
            type: integer
            minimum: 0
            maximum: 100
      examples: 
        - headers: 
            my-app-header: 100
```

### To reproduce...

1. Go to https://editor-next.swagger.io/
2. Paste in the above AsyncAPI definition

### Expected behavior
No validation error appears as the content of `$.components.messageTraits.commonHeaders.examples` is spec compliant

### Screenshots

![image](https://github.com/swagger-api/apidom/assets/96050034/39d7241d-e68f-4018-b219-31bbcc657a84)
